import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainMenu from "./pages/MainMenu/page";
import Footer from "./pages/Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
        {/* Common Header */}
        <MainMenu />
        {/* Main Content */}
        <main className="flex-1 flex flex-col">{children}</main>
        {/* Common Footer */}
        <Footer />
        {/* Global Styles */}
      </body>
    </html>
  );
}